inputTable = {'spectra 1', 'Sample_BSP_Water_rpts_schemes_gpos_delays.mat';...
              'spectra 2', 'Sample_BSP_Water_rpts_schemes_gpos_delays.mat';...
              'spectra 3', 'Sample_BSP_Water_rpts_schemes_gpos_delays.mat'};    

myTS = transientSpectra(inputTable(:,2),'shortName',inputTable(:,1));